name: Build PopcornTimeTV

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Xcode Select
      run: |
        sudo xcode-select -s /Applications/$(ls /Applications | grep -E '^Xcode.*\.app$' | sort -rV | head -n 1)
        sudo xcodebuild -license accept

    - name: Use cache
      id: cache
      uses: actions/cache@v2
      with:
        path: |
          Pods
          vendor/bundle
        key: ${{ runner.os }}-pods-${{ hashFiles('Podfile') }}-gems-${{ hashFiles('Gemfile') }}
        restore-keys: |
          ${{ runner.os }}-pods-${{ hashFiles('Podfile') }}-
          ${{ runner.os }}-gems-${{ hashFiles('Gemfile') }}-

    - name: Ensure Bundler and CocoaPods are Installed
      run: |
        gem install bundler
        gem install cocoapods

    - name: Regenerate Gemfile.lock and Podfile.lock
      run: |
        # Ensure the correct version of CocoaPods is used
        bundle exec pod --version
        # Update CocoaPods repositories
        bundle exec pod repo update
        # Regenerate lock files
        bundle update
        bundle exec pod install --repo-update || { echo "Pod install failed"; exit 1; }

    - name: Check Reachability Repository
      run: |
        # Verify that Reachability repository is accessible
        curl -s --head https://github.com/tonymillion/Reachability | head -n 10

    - name: Build PopcornTime Archive
      run: |
        set -o pipefail && \
        xcodebuild archive \
        -archivePath $RUNNER_TEMP/popcorntime.xcarchive \
        -project PopcornTime.xcodeproj \
        -scheme PopcornTimetvOS \
        -sdk appletvsdk \
        -configuration Debug \
        CODE_SIGNING_REQUIRED=NO \
        CODE_SIGNING_ALLOWED=NO

    - name: Generate unsigned debug IPA
      run: |
        cd ~
        mkdir Payload
        mv ~/Library/Developer/Xcode/Archives/*/*/Products/Applications/*.app ~/Payload/
        zip -r PopcornTimeTV.ipa Payload

    - name: Upload IPA
      uses: actions/upload-artifact@v2.2.0
      with:
        name: 'PopcornTimeTV'
        path: ~/PopcornTimeTV.ipa
