name: Build PopcornTimeTV

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Xcode Select
      run: |
        sudo xcode-select -s /Applications/$(ls /Applications | grep -E '^Xcode.*\.app$' | sort -rV | head -n 1)
        sudo xcodebuild -license accept

    - name: use cache
      id: cache
      uses: actions/cache@v2
      with:
        path: Frameworks
        key: ${{ runner.os }}-${{ hashFiles('Podfile') }}-${{ hashFiles('Gemfile') }}

    - name: get dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        gem install bundler
        bundle install
        pod repo update
        pod install
  
    - name: Build the XCode Project
      run: |
        set -o pipefail && \
        xcodebuild archive \
        -project PopcornTime.xcodeproj \
        -scheme PopcornTimetvOS \
        -sdk appletvos \
        -configuration Debug clean build CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO APPLICATION_EXTENSION_API_ONLY=YES CODE_SIGN_IDENTITY=''

    - name: generate unsigned debug ipa
      run: |
        cd ~
        mkdir Payload
        mv ~/Library/Developer/Xcode/Archives/*/*/Products/Applications/*.app ~/Payload/
        zip -r PopcornTime.ipa Payload

    - name: upload ipa
      uses: actions/upload-artifact@v2.2.0
      with:
        name: 'PopcornTimeTV'
        path: ~/PopcornTime.ipa
