name: "Build tvOS App (Unsigned IPA)"

on:
  workflow_dispatch:

jobs:
  build_unsigned:
    runs-on: macos-latest
    steps:
      - name: Check Xcode version
        run: /usr/bin/xcodebuild -version

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build archive
        run: |
          xcodebuild -scheme "PopcornTimetvOS" \
          -archivePath $RUNNER_TEMP/popcorntime.xcarchive \
          -sdk appletvsdk \
          -configuration Debug \
          -destination generic/platform=tvOS \
          clean archive \
          CODE_SIGNING_REQUIRED=NO \
          CODE_SIGNING_ALLOWED=NO

      - name: Generate Unsigned Debug IPA
        run: |
          mkdir -p ~/Payload
          mv $RUNNER_TEMP/popcorntime.xcarchive/Products/Applications/*.app ~/Payload/
          zip -r ~/PopcornTimeTvOS.ipa ~/Payload

      - name: Upload IPA
        uses: actions/upload-artifact@v3
        with:
          name: 'PopcornTimeTvOS'
          path: ~/PopcornTimeTvOS.ipa
          retention-days: 3
